{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.1",
	"cveMetadata": {
		"cveId": "CVE-2025-0290",
		"assignerOrgId": "ceab7361-8a18-47b1-92ba-4d7d25f6715a",
		"assignerShortName": "GitLab",
		"state": "PUBLISHED",
		"datePublished": "2025-01-28T08:45:09.560Z",
		"dateUpdated": "2025-01-28T08:45:09.560Z",
		"dateReserved": "2025-01-06T22:30:48.611Z"
	},
	"containers": {
		"cna": {
			"providerMetadata": {
				"orgID": "ceab7361-8a18-47b1-92ba-4d7d25f6715a",
				"shortName": "GitLab",
				"dateUpdated": "2025-01-28T08:45:09.560Z"
			},
			"title": "Loop with Unreachable Exit Condition ('Infinite Loop') in GitLab",
			"descriptions": [
				{
					"lang": "en",
					"value": "An issue has been discovered in GitLab CE/EE affecting all versions starting from 15.0 prior to 17.5.5, from 17.6 prior to 17.6.3, and from 17.7 prior to 17.7.1. Under certain conditions, processing of CI artifacts metadata could cause background jobs to become unresponsive."
				}
			],
			"affected": [
				{
					"vendor": "GitLab",
					"product": "GitLab",
					"cpes": [
						"cpe:2.3:a:gitlab:gitlab:*:*:*:*:*:*:*:*"
					],
					"repo": "git://git@gitlab.com:gitlab-org/gitlab.git",
					"defaultStatus": "unaffected",
					"versions": [
						{
							"status": "affected",
							"versionType": "semver",
							"version": "15.0",
							"lessThan": "17.6.4"
						},
						{
							"status": "affected",
							"versionType": "semver",
							"version": "17.7",
							"lessThan": "17.7.2"
						},
						{
							"status": "affected",
							"versionType": "semver",
							"version": "17.8",
							"lessThan": "17.8.0"
						}
					]
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"type": "CWE",
							"lang": "en",
							"description": "CWE-835: Loop with Unreachable Exit Condition ('Infinite Loop')",
							"cweId": "CWE-835"
						}
					]
				}
			],
			"metrics": [
				{
					"format": "CVSS",
					"scenarios": [
						{
							"lang": "en",
							"value": "GENERAL"
						}
					],
					"cvssV3_1": {
						"version": "3.1",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L",
						"attackVector": "NETWORK",
						"attackComplexity": "LOW",
						"privilegesRequired": "LOW",
						"userInteraction": "NONE",
						"scope": "UNCHANGED",
						"confidentialityImpact": "NONE",
						"integrityImpact": "NONE",
						"availabilityImpact": "LOW",
						"baseScore": 4.3,
						"baseSeverity": "MEDIUM"
					}
				}
			],
			"solutions": [
				{
					"lang": "en",
					"value": "Upgrade to versions 17.6.4, 17.7.2, 17.8.0 or above."
				}
			],
			"references": [
				{
					"name": "GitLab Issue #372134",
					"tags": [
						"issue-tracking",
						"permissions-required"
					],
					"url": "https://gitlab.com/gitlab-org/gitlab/-/issues/372134"
				}
			],
			"credits": [
				{
					"type": "finder",
					"lang": "en",
					"value": "This vulnerability was discovered internally by GitLab team member [Stan Hu](https://gitlab.com/stanhu)."
				}
			]
		}
	}
}
