{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.1",
	"cveMetadata": {
		"cveId": "CVE-2023-30996",
		"assignerOrgId": "9a959283-ebb5-44b6-b705-dcc2bbced522",
		"assignerShortName": "ibm",
		"state": "PUBLISHED",
		"datePublished": "2024-02-24T15:35:48.371Z",
		"dateUpdated": "2024-02-24T15:35:48.371Z",
		"dateReserved": "2023-04-21T17:49:51.826Z"
	},
	"containers": {
		"cna": {
			"providerMetadata": {
				"orgID": "9a959283-ebb5-44b6-b705-dcc2bbced522",
				"shortName": "ibm",
				"dateUpdated": "2024-02-24T15:35:48.371Z"
			},
			"title": "IBM Cognos Analytics cross-origin resource sharing",
			"descriptions": [
				{
					"lang": "en",
					"value": "IBM Cognos Analytics 11.1.7, 11.2.4, and 12.0.0 could be vulnerable to information leakage due to unverified sources in messages sent between Windows objects of different origins.  IBM X-Force ID:  254290.",
					"supportingMedia": [
						{
							"type": "text/html",
							"base64": false,
							"value": "IBM Cognos Analytics 11.1.7, 11.2.4, and 12.0.0 could be vulnerable to information leakage due to unverified sources in messages sent between Windows objects of different origins.  IBM X-Force ID:  254290."
						}
					]
				}
			],
			"affected": [
				{
					"vendor": "IBM",
					"product": "Cognos Analytics",
					"defaultStatus": "unaffected",
					"versions": [
						{
							"status": "affected",
							"version": "11.1.7, 11.2.4, 12.0.0"
						}
					]
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"type": "CWE",
							"lang": "en",
							"description": "CWE-346 Origin Validation Error",
							"cweId": "CWE-346"
						}
					]
				}
			],
			"metrics": [
				{
					"format": "CVSS",
					"scenarios": [
						{
							"lang": "en",
							"value": "GENERAL"
						}
					],
					"cvssV3_1": {
						"version": "3.1",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
						"attackVector": "NETWORK",
						"attackComplexity": "LOW",
						"privilegesRequired": "NONE",
						"userInteraction": "NONE",
						"scope": "UNCHANGED",
						"confidentialityImpact": "LOW",
						"integrityImpact": "NONE",
						"availabilityImpact": "NONE",
						"baseScore": 5.3,
						"baseSeverity": "MEDIUM"
					}
				}
			],
			"references": [
				{
					"tags": [
						"vendor-advisory"
					],
					"url": "https://www.ibm.com/support/pages/node/7123154"
				},
				{
					"tags": [
						"vdb-entry"
					],
					"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/254290"
				},
				{
					"url": "https://security.netapp.com/advisory/ntap-20240405-0004/"
				},
				{
					"url": "https://security.netapp.com/advisory/ntap-20240621-0006/"
				}
			],
			"source": {
				"discovery": "UNKNOWN"
			},
			"x_generator": {
				"engine": "Vulnogram 0.1.0-dev"
			}
		}
	}
}
