{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.1",
	"cveMetadata": {
		"cveId": "CVE-2023-47630",
		"assignerOrgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
		"assignerShortName": "GitHub_M",
		"state": "PUBLISHED",
		"datePublished": "2023-11-14T20:59:46.100Z",
		"dateUpdated": "2024-08-02T21:16:42.282Z",
		"dateReserved": "2023-11-07T16:57:49.244Z"
	},
	"containers": {
		"cna": {
			"providerMetadata": {
				"orgID": "a0819718-46f1-4df5-94e2-005712e83aaa",
				"shortName": "GitHub_M",
				"dateUpdated": "2023-11-14T20:59:46.100Z"
			},
			"title": "Attacker can cause Kyverno user to unintentionally consume insecure image",
			"descriptions": [
				{
					"lang": "en",
					"value": "Kyverno is a policy engine designed for Kubernetes. An issue was found in Kyverno that allowed an attacker to control the digest of images used by Kyverno users. The issue would require the attacker to compromise the registry that the Kyverno users fetch their images from. The attacker could then return an vulnerable image to the the user and leverage that to further escalate their position. As such, the attacker would need to know which images the Kyverno user consumes and know of one of multiple exploitable vulnerabilities in previous digests of the images. Alternatively, if the attacker has compromised the registry, they could craft a malicious image with a different digest with intentionally placed vulnerabilities and deliver the image to the user.  Users pulling their images by digests and from trusted registries are not impacted by this vulnerability. There is no evidence of this being exploited in the wild. The issue has been patched in 1.10.5. All users are advised to upgrade. There are no known workarounds for this vulnerability."
				}
			],
			"affected": [
				{
					"vendor": "kyverno",
					"product": "kyverno",
					"versions": [
						{
							"status": "affected",
							"version": "< 1.10.5"
						}
					]
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"type": "CWE",
							"lang": "en",
							"description": "CWE-345: Insufficient Verification of Data Authenticity",
							"cweId": "CWE-345"
						}
					]
				}
			],
			"metrics": [
				{
					"cvssV3_1": {
						"version": "3.1",
						"vectorString": "CVSS:3.1/AV:N/AC:H/PR:L/UI:R/S:U/C:H/I:H/A:H",
						"attackVector": "NETWORK",
						"attackComplexity": "HIGH",
						"privilegesRequired": "LOW",
						"userInteraction": "REQUIRED",
						"scope": "UNCHANGED",
						"confidentialityImpact": "HIGH",
						"integrityImpact": "HIGH",
						"availabilityImpact": "HIGH",
						"baseScore": 7.1,
						"baseSeverity": "HIGH"
					}
				}
			],
			"references": [
				{
					"name": "https://github.com/kyverno/kyverno/security/advisories/GHSA-3hfq-cx9j-923w",
					"tags": [
						"x_refsource_CONFIRM"
					],
					"url": "https://github.com/kyverno/kyverno/security/advisories/GHSA-3hfq-cx9j-923w"
				}
			],
			"source": {
				"advisory": "GHSA-3hfq-cx9j-923w",
				"discovery": "UNKNOWN"
			}
		},
		"adp": [
			{
				"providerMetadata": {
					"orgID": "af854a3a-2127-422b-91ae-364da2661108",
					"shortName": "CVE",
					"dateUpdated": "2024-08-02T21:16:42.282Z"
				},
				"title": "CVE Program Container",
				"references": [
					{
						"name": "https://github.com/kyverno/kyverno/security/advisories/GHSA-3hfq-cx9j-923w",
						"tags": [
							"x_refsource_CONFIRM",
							"x_transferred"
						],
						"url": "https://github.com/kyverno/kyverno/security/advisories/GHSA-3hfq-cx9j-923w"
					}
				]
			}
		]
	}
}
