{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.1",
	"cveMetadata": {
		"cveId": "CVE-2023-26272",
		"assignerOrgId": "9a959283-ebb5-44b6-b705-dcc2bbced522",
		"assignerShortName": "ibm",
		"state": "PUBLISHED",
		"datePublished": "2023-08-28T00:05:48.844Z",
		"dateUpdated": "2024-08-02T11:46:23.905Z",
		"dateReserved": "2023-02-21T13:55:23.669Z"
	},
	"containers": {
		"cna": {
			"providerMetadata": {
				"orgID": "9a959283-ebb5-44b6-b705-dcc2bbced522",
				"shortName": "ibm",
				"dateUpdated": "2023-08-28T00:05:48.844Z"
			},
			"title": "IBM Security Guardium Data Encryption information disclosure",
			"descriptions": [
				{
					"lang": "en",
					"value": "IBM Security Guardium Data Encryption (IBM Guardium Cloud Key Manager (GCKM) 1.10.3)) could allow a remote attacker to obtain sensitive information when a detailed technical error message is returned in the browser.  This information could be used in further attacks against the system.  IBM X-Force ID:  248133.",
					"supportingMedia": [
						{
							"type": "text/html",
							"base64": false,
							"value": "IBM Security Guardium Data Encryption (IBM Guardium Cloud Key Manager (GCKM) 1.10.3)) could allow a remote attacker to obtain sensitive information when a detailed technical error message is returned in the browser.  This information could be used in further attacks against the system.  IBM X-Force ID:  248133."
						}
					]
				}
			],
			"affected": [
				{
					"vendor": "IBM",
					"product": "Guardium Cloud Key Manager",
					"defaultStatus": "unaffected",
					"versions": [
						{
							"status": "affected",
							"version": "1.10.3"
						}
					]
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"type": "CWE",
							"lang": "en",
							"description": "CWE-209 Generation of Error Message Containing Sensitive Information",
							"cweId": "CWE-209"
						}
					]
				}
			],
			"metrics": [
				{
					"format": "CVSS",
					"scenarios": [
						{
							"lang": "en",
							"value": "GENERAL"
						}
					],
					"cvssV3_1": {
						"version": "3.1",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
						"attackVector": "NETWORK",
						"attackComplexity": "LOW",
						"privilegesRequired": "NONE",
						"userInteraction": "NONE",
						"scope": "UNCHANGED",
						"confidentialityImpact": "LOW",
						"integrityImpact": "NONE",
						"availabilityImpact": "NONE",
						"baseScore": 5.3,
						"baseSeverity": "MEDIUM"
					}
				}
			],
			"references": [
				{
					"tags": [
						"vendor-advisory"
					],
					"url": "https://www.ibm.com/support/pages/node/6995161"
				},
				{
					"tags": [
						"vdb-entry"
					],
					"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/248133"
				}
			],
			"source": {
				"discovery": "UNKNOWN"
			},
			"x_generator": {
				"engine": "Vulnogram 0.1.0-dev"
			}
		},
		"adp": [
			{
				"providerMetadata": {
					"orgID": "af854a3a-2127-422b-91ae-364da2661108",
					"shortName": "CVE",
					"dateUpdated": "2024-08-02T11:46:23.905Z"
				},
				"title": "CVE Program Container",
				"references": [
					{
						"tags": [
							"vendor-advisory",
							"x_transferred"
						],
						"url": "https://www.ibm.com/support/pages/node/6995161"
					},
					{
						"tags": [
							"vdb-entry",
							"x_transferred"
						],
						"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/248133"
					}
				]
			}
		]
	}
}
