{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.1",
	"cveMetadata": {
		"cveId": "CVE-2019-4533",
		"assignerOrgId": "9a959283-ebb5-44b6-b705-dcc2bbced522",
		"assignerShortName": "ibm",
		"state": "PUBLISHED",
		"datePublished": "2020-08-28T14:35:19.141907Z",
		"dateUpdated": "2024-09-16T18:18:53.865Z",
		"dateReserved": "2019-01-03T00:00:00"
	},
	"containers": {
		"cna": {
			"providerMetadata": {
				"orgID": "9a959283-ebb5-44b6-b705-dcc2bbced522",
				"shortName": "ibm",
				"dateUpdated": "2020-08-28T14:35:19"
			},
			"descriptions": [
				{
					"lang": "en",
					"value": "IBM Resilient SOAR V38.0 users may experience a denial of service of the SOAR Platform due to a insufficient input validation. IBM X-Force ID: 165589."
				}
			],
			"affected": [
				{
					"vendor": "IBM",
					"product": "Resilient SOAR",
					"versions": [
						{
							"status": "affected",
							"version": "38"
						}
					]
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"type": "text",
							"lang": "en",
							"description": "Denial of Service"
						}
					]
				}
			],
			"metrics": [
				{
					"cvssV3_0": {
						"version": "3.0",
						"vectorString": "CVSS:3.0/I:N/PR:L/AV:N/C:N/S:U/AC:L/A:L/UI:N/RL:O/RC:C/E:U",
						"attackVector": "NETWORK",
						"attackComplexity": "LOW",
						"privilegesRequired": "LOW",
						"userInteraction": "NONE",
						"scope": "UNCHANGED",
						"confidentialityImpact": "NONE",
						"integrityImpact": "NONE",
						"availabilityImpact": "LOW",
						"baseScore": 4.3,
						"baseSeverity": "MEDIUM",
						"exploitCodeMaturity": "UNPROVEN",
						"remediationLevel": "OFFICIAL_FIX",
						"reportConfidence": "CONFIRMED",
						"temporalScore": 3.8,
						"temporalSeverity": "LOW"
					}
				}
			],
			"references": [
				{
					"tags": [
						"x_refsource_CONFIRM"
					],
					"url": "https://www.ibm.com/support/pages/node/6323645"
				},
				{
					"name": "ibm-resilient-cve20194533-dos (165589)",
					"tags": [
						"vdb-entry",
						"x_refsource_XF"
					],
					"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/165589"
				}
			],
			"datePublic": "2020-08-27T00:00:00",
			"x_legacyV4Record": {
				"CVE_data_meta": {
					"ASSIGNER": "psirt@us.ibm.com",
					"DATE_PUBLIC": "2020-08-27T00:00:00",
					"ID": "CVE-2019-4533",
					"STATE": "PUBLIC"
				},
				"affects": {
					"vendor": {
						"vendor_data": [
							{
								"product": {
									"product_data": [
										{
											"product_name": "Resilient SOAR",
											"version": {
												"version_data": [
													{
														"version_value": "38"
													}
												]
											}
										}
									]
								},
								"vendor_name": "IBM"
							}
						]
					}
				},
				"data_format": "MITRE",
				"data_type": "CVE",
				"data_version": "4.0",
				"description": {
					"description_data": [
						{
							"lang": "eng",
							"value": "IBM Resilient SOAR V38.0 users may experience a denial of service of the SOAR Platform due to a insufficient input validation. IBM X-Force ID: 165589."
						}
					]
				},
				"impact": {
					"cvssv3": {
						"BM": {
							"A": "L",
							"AC": "L",
							"AV": "N",
							"C": "N",
							"I": "N",
							"PR": "L",
							"S": "U",
							"UI": "N"
						},
						"TM": {
							"E": "U",
							"RC": "C",
							"RL": "O"
						}
					}
				},
				"problemtype": {
					"problemtype_data": [
						{
							"description": [
								{
									"lang": "eng",
									"value": "Denial of Service"
								}
							]
						}
					]
				},
				"references": {
					"reference_data": [
						{
							"name": "https://www.ibm.com/support/pages/node/6323645",
							"refsource": "CONFIRM",
							"title": "IBM Security Bulletin 6323645 (Resilient SOAR)",
							"url": "https://www.ibm.com/support/pages/node/6323645"
						},
						{
							"name": "ibm-resilient-cve20194533-dos (165589)",
							"refsource": "XF",
							"title": "X-Force Vulnerability Report",
							"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/165589"
						}
					]
				}
			}
		},
		"adp": [
			{
				"providerMetadata": {
					"orgID": "af854a3a-2127-422b-91ae-364da2661108",
					"shortName": "CVE",
					"dateUpdated": "2024-08-04T19:40:47.323Z"
				},
				"title": "CVE Program Container",
				"references": [
					{
						"tags": [
							"x_refsource_CONFIRM",
							"x_transferred"
						],
						"url": "https://www.ibm.com/support/pages/node/6323645"
					},
					{
						"name": "ibm-resilient-cve20194533-dos (165589)",
						"tags": [
							"vdb-entry",
							"x_refsource_XF",
							"x_transferred"
						],
						"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/165589"
					}
				]
			}
		]
	}
}
