{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.1",
	"cveMetadata": {
		"cveId": "CVE-2021-38578",
		"assignerOrgId": "65518388-201a-4f93-8712-366d21fe8d2c",
		"assignerShortName": "TianoCore",
		"state": "PUBLISHED",
		"datePublished": "2022-03-03T21:53:37",
		"dateUpdated": "2024-08-06T00:55:57.322Z",
		"dateReserved": "2021-08-11T00:00:00"
	},
	"containers": {
		"cna": {
			"providerMetadata": {
				"orgID": "65518388-201a-4f93-8712-366d21fe8d2c",
				"shortName": "TianoCore",
				"dateUpdated": "2024-08-06T00:55:57.322Z"
			},
			"descriptions": [
				{
					"lang": "en",
					"value": "Existing CommBuffer checks in SmmEntryPoint will not catch underflow when computing BufferSize.",
					"supportingMedia": [
						{
							"type": "text/html",
							"base64": false,
							"value": "<p>Existing CommBuffer checks in SmmEntryPoint will not catch underflow when computing BufferSize.</p>"
						}
					]
				}
			],
			"affected": [
				{
					"vendor": "TianoCore",
					"product": "EDK II",
					"defaultStatus": "unaffected",
					"versions": [
						{
							"status": "affected",
							"version": "edk2-stable202208"
						}
					]
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"type": "CWE",
							"lang": "en",
							"description": "A case of CWE-124 is occurring in PiSmmCore.",
							"cweId": "CWE-124"
						}
					]
				}
			],
			"metrics": [
				{
					"format": "CVSS",
					"scenarios": [
						{
							"lang": "en",
							"value": "GENERAL"
						}
					],
					"cvssV3_1": {
						"version": "3.1",
						"vectorString": "CVSS:3.1/AV:L/AC:H/PR:H/UI:N/S:C/C:H/I:H/A:L",
						"attackVector": "LOCAL",
						"attackComplexity": "HIGH",
						"privilegesRequired": "HIGH",
						"userInteraction": "NONE",
						"scope": "CHANGED",
						"confidentialityImpact": "HIGH",
						"integrityImpact": "HIGH",
						"availabilityImpact": "LOW",
						"baseScore": 7.4,
						"baseSeverity": "HIGH"
					}
				}
			],
			"references": [
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://bugzilla.tianocore.org/show_bug.cgi?id=3387"
				},
				{
					"url": "https://www.insyde.com/security-pledge/SA-2023024"
				}
			],
			"source": {
				"discovery": "UNKNOWN"
			},
			"x_generator": {
				"engine": "Vulnogram 0.1.0-dev"
			}
		},
		"adp": [
			{
				"providerMetadata": {
					"orgID": "af854a3a-2127-422b-91ae-364da2661108",
					"shortName": "CVE",
					"dateUpdated": "2024-08-04T01:44:23.499Z"
				},
				"title": "CVE Program Container",
				"references": [
					{
						"tags": [
							"x_refsource_MISC",
							"x_transferred"
						],
						"url": "https://bugzilla.tianocore.org/show_bug.cgi?id=3387"
					},
					{
						"tags": [
							"x_transferred"
						],
						"url": "https://www.insyde.com/security-pledge/SA-2023024"
					}
				]
			}
		]
	}
}
