{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.0",
	"cveMetadata": {
		"cveId": "CVE-2021-4150",
		"assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
		"assignerShortName": "redhat",
		"state": "PUBLISHED",
		"datePublished": "2022-03-23T19:46:46",
		"dateUpdated": "2022-03-23T19:46:46",
		"dateReserved": "2021-12-21T00:00:00"
	},
	"containers": {
		"cna": {
			"providerMetadata": {
				"orgID": "53f830b8-0a3f-465b-8143-3b8a9948e749",
				"shortName": "redhat",
				"dateUpdated": "2022-03-23T19:46:46"
			},
			"descriptions": [
				{
					"lang": "en",
					"value": "A use-after-free flaw was found in the add_partition in block/partitions/core.c in the Linux kernel. A local attacker with user privileges could cause a denial of service on the system. The issue results from the lack of code cleanup when device_add call fails when adding a partition to the disk."
				}
			],
			"affected": [
				{
					"vendor": "n/a",
					"product": "kernel",
					"versions": [
						{
							"status": "affected",
							"version": "kernel 5.15 rc7"
						}
					]
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"type": "CWE",
							"lang": "en",
							"description": "CWE-416",
							"cweId": "CWE-416"
						}
					]
				}
			],
			"references": [
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2025938"
				},
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://lkml.org/lkml/2021/10/18/485"
				},
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://lkml.org/lkml/2021/9/6/781"
				}
			],
			"x_legacyV4Record": {
				"CVE_data_meta": {
					"ASSIGNER": "secalert@redhat.com",
					"ID": "CVE-2021-4150",
					"STATE": "PUBLIC"
				},
				"affects": {
					"vendor": {
						"vendor_data": [
							{
								"product": {
									"product_data": [
										{
											"product_name": "kernel",
											"version": {
												"version_data": [
													{
														"version_value": "kernel 5.15 rc7"
													}
												]
											}
										}
									]
								},
								"vendor_name": "n/a"
							}
						]
					}
				},
				"data_format": "MITRE",
				"data_type": "CVE",
				"data_version": "4.0",
				"description": {
					"description_data": [
						{
							"lang": "eng",
							"value": "A use-after-free flaw was found in the add_partition in block/partitions/core.c in the Linux kernel. A local attacker with user privileges could cause a denial of service on the system. The issue results from the lack of code cleanup when device_add call fails when adding a partition to the disk."
						}
					]
				},
				"problemtype": {
					"problemtype_data": [
						{
							"description": [
								{
									"lang": "eng",
									"value": "CWE-416"
								}
							]
						}
					]
				},
				"references": {
					"reference_data": [
						{
							"name": "https://bugzilla.redhat.com/show_bug.cgi?id=2025938",
							"refsource": "MISC",
							"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2025938"
						},
						{
							"name": "https://lkml.org/lkml/2021/10/18/485",
							"refsource": "MISC",
							"url": "https://lkml.org/lkml/2021/10/18/485"
						},
						{
							"name": "https://lkml.org/lkml/2021/9/6/781",
							"refsource": "MISC",
							"url": "https://lkml.org/lkml/2021/9/6/781"
						}
					]
				}
			}
		}
	}
}
