{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.1",
	"cveMetadata": {
		"cveId": "CVE-2021-43313",
		"assignerOrgId": "92fb86c3-55a5-4fb5-9c3f-4757b9e96dc5",
		"assignerShortName": "fedora",
		"state": "PUBLISHED",
		"datePublished": "2023-03-24T00:00:00",
		"dateUpdated": "2024-08-04T03:55:28.556Z",
		"dateReserved": "2021-11-03T00:00:00"
	},
	"containers": {
		"cna": {
			"providerMetadata": {
				"orgID": "92fb86c3-55a5-4fb5-9c3f-4757b9e96dc5",
				"shortName": "fedora",
				"dateUpdated": "2023-03-24T00:00:00"
			},
			"descriptions": [
				{
					"lang": "en",
					"value": "A heap-based buffer overflow was discovered in upx, during the variable 'bucket' points to an inaccessible address. The issue is being triggered in the function PackLinuxElf32::invert_pt_dynamic at p_lx_elf.cpp:1688."
				}
			],
			"affected": [
				{
					"vendor": "n/a",
					"product": "upx",
					"versions": [
						{
							"status": "affected",
							"version": "upx before 4.0.0-git-c6b9e3c62d15"
						}
					]
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"type": "CWE",
							"lang": "en",
							"description": "CWE-119",
							"cweId": "CWE-119"
						}
					]
				}
			],
			"references": [
				{
					"url": "https://github.com/upx/upx/issues/378"
				}
			]
		},
		"adp": [
			{
				"providerMetadata": {
					"orgID": "af854a3a-2127-422b-91ae-364da2661108",
					"shortName": "CVE",
					"dateUpdated": "2024-08-04T03:55:28.556Z"
				},
				"title": "CVE Program Container",
				"references": [
					{
						"tags": [
							"x_transferred"
						],
						"url": "https://github.com/upx/upx/issues/378"
					}
				]
			}
		]
	}
}
