{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.1",
	"cveMetadata": {
		"cveId": "CVE-2013-4347",
		"assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
		"assignerShortName": "redhat",
		"state": "PUBLISHED",
		"datePublished": "2014-05-20T14:00:00",
		"dateUpdated": "2024-08-06T16:38:01.910Z",
		"dateReserved": "2013-06-12T00:00:00"
	},
	"containers": {
		"cna": {
			"providerMetadata": {
				"orgID": "53f830b8-0a3f-465b-8143-3b8a9948e749",
				"shortName": "redhat",
				"dateUpdated": "2016-11-25T19:57:01"
			},
			"descriptions": [
				{
					"lang": "en",
					"value": "The (1) make_nonce, (2) generate_nonce, and (3) generate_verifier functions in SimpleGeo python-oauth2 uses weak random numbers to generate nonces, which makes it easier for remote attackers to guess the nonce via a brute force attack."
				}
			],
			"affected": [
				{
					"vendor": "n/a",
					"product": "n/a",
					"versions": [
						{
							"status": "affected",
							"version": "n/a"
						}
					]
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"type": "text",
							"lang": "en",
							"description": "n/a"
						}
					]
				}
			],
			"references": [
				{
					"name": "62388",
					"tags": [
						"vdb-entry",
						"x_refsource_BID"
					],
					"url": "http://www.securityfocus.com/bid/62388"
				},
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://github.com/simplegeo/python-oauth2/issues/9"
				},
				{
					"name": "[oss-security] 20130912 Re: cve requests for python-oauth2",
					"tags": [
						"mailing-list",
						"x_refsource_MLIST"
					],
					"url": "http://www.openwall.com/lists/oss-security/2013/09/12/7"
				},
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://github.com/simplegeo/python-oauth2/pull/146"
				}
			],
			"datePublic": "2010-04-24T00:00:00"
		},
		"adp": [
			{
				"providerMetadata": {
					"orgID": "af854a3a-2127-422b-91ae-364da2661108",
					"shortName": "CVE",
					"dateUpdated": "2024-08-06T16:38:01.910Z"
				},
				"title": "CVE Program Container",
				"references": [
					{
						"name": "62388",
						"tags": [
							"vdb-entry",
							"x_refsource_BID",
							"x_transferred"
						],
						"url": "http://www.securityfocus.com/bid/62388"
					},
					{
						"tags": [
							"x_refsource_MISC",
							"x_transferred"
						],
						"url": "https://github.com/simplegeo/python-oauth2/issues/9"
					},
					{
						"name": "[oss-security] 20130912 Re: cve requests for python-oauth2",
						"tags": [
							"mailing-list",
							"x_refsource_MLIST",
							"x_transferred"
						],
						"url": "http://www.openwall.com/lists/oss-security/2013/09/12/7"
					},
					{
						"tags": [
							"x_refsource_MISC",
							"x_transferred"
						],
						"url": "https://github.com/simplegeo/python-oauth2/pull/146"
					}
				]
			}
		]
	}
}
